### ISSUE TITLE
Issues with 1.4.0

### ISSUE THREAD

**Issue by lymanepp** [dolezsa/thermal_comfort#115]
I'm getting the following error after migrating to the new configuration format:
```
2022-01-31 12:08:51 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up thermal_comfort platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermal_comfort/sensor.py", line 282, in async_setup_platform
    sensors += [
  File "/config/custom_components/thermal_comfort/sensor.py", line 283, in <listcomp>
    SensorThermalComfort(
  File "/config/custom_components/thermal_comfort/sensor.py", line 369, in __init__
    f"{self._device.name} {self._sensor_type.to_title()}"
AttributeError: 'str' object has no attribute 'to_title'
```

Here's a subset of my configuration:
```
thermal_comfort:
  - sensor:
      - name: Garage
        temperature_sensor: sensor.garage_temperature
        humidity_sensor: sensor.garage_humidity
        unique_id: garage
        sensor_types:
          - absolute_humidity
          - dew_point
          - simmer_index
```

**Comment by rautesamtr** [comment]
Sorry for that
