### ISSUE TITLE
Error after updating to 1.4.2

### ISSUE THREAD

**Issue by MoonlightGuest** [dolezsa/thermal_comfort#126]
The next error appear after update to 1.4.2:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermal_comfort/sensor.py", line 324, in async_setup_entry
    scan_interval=timedelta(seconds=data[CONF_SCAN_INTERVAL]),
TypeError: unsupported type for timedelta seconds component: NoneType
```
All sensors are in the Unavailable state.

Home Assistant version 2022.2.0b5
HACS version:  1.21.0

**Comment by rautesamtr** [comment]
probably fixed in #122 will publish new release in the next hours

**Comment by rautesamtr** [comment]
Sorry for the inconvenience. Could you test 1.4.3?

**Comment by MoonlightGuest** [comment]
No probs. It works now on 1.4.3.
Thank you for the prompt fixing!
