### ISSUE TITLE
Error doing job: Future exception was never retrieved

### ISSUE THREAD

**Issue by urielz** [dolezsa/thermal_comfort#14]
Hello,

I have the component up and running just fine but I'm getting these errors every now and then, has anyone experience them as well? Any solutions? Thanks..

```
Logger: homeassistant
Source: custom_components/thermal_comfort/sensor.py:118
Integration: thermal_comfort (documentation)
First occurred: May 20, 2021, 10:13:53 PM (44 occurrences)
Last logged: May 21, 2021, 11:59:35 AM

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/thermal_comfort/sensor.py", line 118, in temperature_state_listener
    self._temperature = float(new_state.state)
ValueError: could not convert string to float: 'unavailable'
```

**Comment by dolezsa** [comment]
fixed

**Comment by urielz** [comment]
Thank you. Looks good on my end.
