### ISSUE TITLE
Not working in home assistant 

### ISSUE THREAD

**Issue by haze1986** [dolezsa/thermal_comfort#206]
Home Assistant 2022.10.0
Supervisor 2022.09.1
Operating System 9.0
Frontend 20221005.0 - latest

Logger: homeassistant.helpers.entity
Source: custom_components/thermal_comfort/sensor.py:604
Integration: Thermal Comfort ([documentation](https://github.com/dolezsa/thermal_comfort/blob/master/README.md), [issues](https://github.com/dolezsa/thermal_comfort/issues))
First occurred: 12:10:41 PM (1326 occurrences)
Last logged: 3:51:11 PM

Update for sensor.mbr_heatindex fails
Update for sensor.study_heatindex fails
Update for sensor.living_heatindex fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/config/custom_components/thermal_comfort/sensor.py", line 446, in async_update
    value = await getattr(self._device, self._sensor_type)()
  File "/config/custom_components/thermal_comfort/sensor.py", line 261, in wrapped
    setattr(self, f"_{sensor_type}", await func(self, *args, **kwargs))
  File "/config/custom_components/thermal_comfort/sensor.py", line 604, in heat_index
    fahrenheit = util.temperature.celsius_to_fahrenheit(self._temperature)
AttributeError: module 'homeassistant.util' has no attribute 'temperature'

**Comment by rautesamtr** [comment]
duplicate #202
