### ISSUE TITLE
Load up failing with newest 2023.12 dev versions

### ISSUE THREAD

**Issue by enkama** [dolezsa/thermal_comfort#322]
On startup with the newest dev version of Homeassistant I get this error:

```
2023-11-21 17:04:36.627 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration thermal_comfort: Unable to import component: cannot import name 'async_log_exception' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 816, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/thermal_comfort/__init__.py", line 22, in <module>
    from .config import OPTIONS_SCHEMA
  File "/config/custom_components/thermal_comfort/config.py", line 4, in <module>
    from homeassistant.config import async_log_exception, config_without_domain
ImportError: cannot import name 'async_log_exception' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
```

**Comment by rautesamtr** [comment]
#319 already fixes this, just waiting till changes are in stable
