### ISSUE TITLE
Setup fails in Home Assistant 2024.1.0b1

### ISSUE THREAD

**Issue by daemonenstall** [dolezsa/thermal_comfort#354]
The integration fails during  setup in Home Assistant 2024.1.0b1

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:360
Integration: Sensor (documentation, issues)
First occurred: 04:39:45 (1 occurrences)
Last logged: 04:39:45

Error while setting up thermal_comfort platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermal_comfort/sensor.py", line 385, in async_setup_platform
    sensors += [
               ^
  File "/config/custom_components/thermal_comfort/sensor.py", line 386, in <listcomp>
    SensorThermalComfort(
  File "/config/custom_components/thermal_comfort/sensor.py", line 480, in __init__
    self.entity_description.translation_key = sensor_type
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'translation_key'

**Comment by rautesamtr** [comment]
Please use the master branch for non stable releases

**Comment by yousaf465** [comment]
installed master branch 
but got this 
![image](https://github.com/dolezsa/thermal_comfort/assets/83491212/9ee8e8d7-5992-4dfd-95c4-0522f9d882e9)

![image](https://github.com/dolezsa/thermal_comfort/assets/83491212/41eda184-761b-4b60-b1ba-10a4e408c83d)

**Comment by rautesamtr** [comment]
That's strange do you have any different error messages? Could you do a clean reinstall of the component?

**Comment by variada** [comment]
I just downloaded the master branch manually and replaced the HACS version.

before and after the same as shown above. everything unavailable.

**Comment by pdsccode** [comment]
I have the same issue since updating to 2024.1b2 but I do have something in the debug log:

`2023-12-30 23:05:40.720 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up thermal_comfort platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermal_comfort/sensor.py", line 435, in async_setup_entry
    entities: list[SensorThermalComfort] = [
                                           ^
  File "/config/custom_components/thermal_comfort/sensor.py", line 436, in <listcomp>
    SensorThermalComfort(
  File "/config/custom_components/thermal_comfort/sensor.py", line 480, in __init__
    self.entity_description.translation_key = sensor_type
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'translation_key'`
