### ISSUE TITLE
HA 2024.1 beta won't create sensors

### ISSUE THREAD

**Issue by LouiS22** [dolezsa/thermal_comfort#357]
Hello there, 
The upcoming version's betas throwing the below error:

Error while setting up thermal_comfort platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermal_comfort/sensor.py", line 435, in async_setup_entry
    entities: list[SensorThermalComfort] = [
                                           ^
  File "/config/custom_components/thermal_comfort/sensor.py", line 436, in <listcomp>
    SensorThermalComfort(
  File "/config/custom_components/thermal_comfort/sensor.py", line 480, in __init__
    self.entity_description.translation_key = sensor_type
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'translation_key'

**Comment by rautesamtr** [comment]
#354
