### ISSUE TITLE
Thermal Comfort stops working in newest HA 2024.1.0

### ISSUE THREAD

**Issue by tigersoul925** [dolezsa/thermal_comfort#360]
After I updated to Home assistant 2024.1.0, Thermal comfort no longer works. I can create the integration and set it up as desired, but there are no entities created and nothing happens. I just updated to the newest version of Thermal comfort via HACS.

Let me know what details you need.

**Comment by rautesamtr** [comment]
Do you have any errors in your logs regarding thermal comfort?

**Comment by tigersoul925** [comment]
I just realized, if I click "configure" and just hit submit again, all entities show up and calculations are being made again, but now everything is enabled and the disabled entires are not respected.

When redoing it with debug logging I get this: (some not related likely, look at the last parts)

`2024-01-04 12:56:25.536 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 883, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 912, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 529, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/melcloud/sensor.py", line 188, in native_value
    return self.entity_description.value_fn(self._api)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/melcloud/sensor.py", line 68, in 
    value_fn=lambda x: x.device.daily_energy_consumed,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymelcloud/device.py", line 210, in daily_energy_consumed
    consumption += self._energy_report.get(mode, [0.0])[-1]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2024-01-04 12:56:26.467 DEBUG (MainThread) [custom_components.thermal_comfort.config_flow] Results for humidity based on device class: ['sensor.balcony_outside_ceiling_humidity', 'sensor.bedroom_room_humidity', 'sensor.kitchen_pantry_humidity', 'sensor.kitchen_room_humidity', 'sensor.kitchen_unused_int_humidity', 'sensor.livingroom_room_humidity', 'sensor.studio_room_humidity']
2024-01-04 12:56:26.490 DEBUG (MainThread) [custom_components.thermal_comfort.config_flow] Additional results: ['input_boolean.autovoice_lan_enabled', 'input_boolean.bedroom_mattress_timer', 'input_boolean.livingroom_pir_sensor_activated', 'input_boolean.main_phone_home_wifi', 'input_boolean.main_phone_nightmode', 'input_boolean.smoke_detector_alarm_sent', 'input_button.all_off', 'input_button.bright_light', 'input_button.helgmys', 'input_button.kvallsmys', 'input_button.movie_lights', 'input_button.night_off', 'input_datetime.rclone_last_successful_run', 'input_number.apartment_energy_spent_cost', 'input_number.kwh_price', 'remember_the_milk.kristian', 'select.harmony_hub_activities', 'sensor.apartment_smoke_detectors_sensor_status', 'sensor.backup_state', 'sensor.balcony_outside_ceiling_humidity_status', 'sensor.bedroom_room_humidity_status', 'sensor.brother_dcp_l2530dw_series', 'sensor.brother_dcp_l2530dw_series_bk', 'sensor.date', 'sensor.dcp_l2530dw_black_toner_remaining', 'sensor.dcp_l2530dw_drum_counter', 'sensor.dcp_l2530dw_drum_remaining_life', 'sensor.dcp_l2530dw_drum_remaining_pages', 'sensor.dcp_l2530dw_duplex_unit_pages_counter', 'sensor.dcp_l2530dw_page_counter', 'sensor.dcp_l2530dw_status', 'sensor.hacs', 'sensor.kitchen_pantry_humidity_status', 'sensor.kitchen_room_humidity_status', 'sensor.kitchen_unused_int_humidity_status', 'sensor.kristians_macbook_pro_active_audio_output', 'sensor.kristians_macbook_pro_active_camera', 'sensor.kristians_macbook_pro_active_microphone', 'sensor.kristians_macbook_pro_bssid', 'sensor.kristians_macbook_pro_connection_type', 'sensor.kristians_macbook_pro_displays', 'sensor.kristians_macbook_pro_frontmost_app', 'sensor.kristians_macbook_pro_geocoded_location', 'sensor.kristians_macbook_pro_internal_battery_state', 'sensor.kristians_macbook_pro_last_update_trigger', 'sensor.kristians_macbook_pro_primary_display_id', 'sensor.kristians_macbook_pro_primary_display_name', 'sensor.kristians_macbook_pro_ssid', 'sensor.kristians_macbook_pro_storage', 'sensor.livingroom_room_humidity_status', 'sensor.load_15m', 'sensor.load_5m', 'sensor.nas_cpu_load_15_min', 'sensor.nas_cpu_load_5_min', 'sensor.nas_cpu_load_total', 'sensor.nas_cpu_load_user', 'sensor.nas_drive_1_status', 'sensor.nas_drive_2_status', 'sensor.nas_memory_usage_real', 'sensor.nas_volume_1_status', 'sensor.nas_volume_1_volume_used', 'sensor.nas_volume_2_status', 'sensor.nas_volume_2_volume_used', 'sensor.nas_volume_3_status', 'sensor.nas_volume_3_volume_used', 'sensor.our_groceries', 'sensor.pixel_7a_battery_state', 'sensor.pixel_7a_charger_type', 'sensor.pixel_7a_detected_activity', 'sensor.pixel_7a_do_not_disturb_sensor', 'sensor.pixel_7a_sleep_confidence', 'sensor.pixel_7a_wifi_connection', 'sensor.processor_use_percent', 'sensor.studio_room_humidity_status', 'sensor.time', 'update.duck_dns_update', 'update.file_editor_update', 'update.glances_update', 'update.grafana_update', 'update.home_assistant_core_update', 'update.home_assistant_google_drive_backup_update', 'update.home_assistant_operating_system_update', 'update.home_assistant_supervisor_update', 'update.influxdb_update', 'update.log_viewer_update', 'update.mariadb_update', 'update.mosquitto_broker_update', 'update.nas_dsm_update', 'update.nginx_proxy_manager_update', 'update.phpmyadmin_update', 'update.portainer_update', 'update.rclone_backup_update', 'update.samba_share_update', 'update.ssh_web_terminal_update', 'update.studio_code_server_update', 'update.unifi_network_application_update', 'update.wireguard_update', 'weather.hem']
2024-01-04 12:56:26.492 DEBUG (MainThread) [custom_components.thermal_comfort.config_flow] Results after cleaning own entities: ['sensor.balcony_outside_ceiling_humidity', 'sensor.bedroom_room_humidity', 'sensor.kitchen_pantry_humidity', 'sensor.kitchen_room_humidity', 'sensor.kitchen_unused_int_humidity', 'sensor.livingroom_room_humidity', 'sensor.studio_room_humidity', 'input_boolean.autovoice_lan_enabled', 'input_boolean.bedroom_mattress_timer', 'input_boolean.livingroom_pir_sensor_activated', 'input_boolean.main_phone_home_wifi', 'input_boolean.main_phone_nightmode', 'input_boolean.smoke_detector_alarm_sent', 'input_button.all_off', 'input_button.bright_light', 'input_button.helgmys', 'input_button.kvallsmys', 'input_button.movie_lights', 'input_button.night_off', 'input_datetime.rclone_last_successful_run', 'input_number.apartment_energy_spent_cost', 'input_number.kwh_price', 'remember_the_milk.kristian', 'select.harmony_hub_activities', 'sensor.apartment_smoke_detectors_sensor_status', 'sensor.backup_state', 'sensor.balcony_outside_ceiling_humidity_status', 'sensor.bedroom_room_humidity_status', 'sensor.brother_dcp_l2530dw_series', 'sensor.brother_dcp_l2530dw_series_bk', 'sensor.date', 'sensor.dcp_l2530dw_black_toner_remaining', 'sensor.dcp_l2530dw_drum_counter', 'sensor.dcp_l2530dw_drum_remaining_life', 'sensor.dcp_l2530dw_drum_remaining_pages', 'sensor.dcp_l2530dw_duplex_unit_pages_counter', 'sensor.dcp_l2530dw_page_counter', 'sensor.dcp_l2530dw_status', 'sensor.hacs', 'sensor.kitchen_pantry_humidity_status', 'sensor.kitchen_room_humidity_status', 'sensor.kitchen_unused_int_humidity_status', 'sensor.kristians_macbook_pro_active_audio_output', 'sensor.kristians_macbook_pro_active_camera', 'sensor.kristians_macbook_pro_active_microphone', 'sensor.kristians_macbook_pro_bssid', 'sensor.kristians_macbook_pro_connection_type', 'sensor.kristians_macbook_pro_displays', 'sensor.kristians_macbook_pro_frontmost_app', 'sensor.kristians_macbook_pro_geocoded_location', 'sensor.kristians_macbook_pro_internal_battery_state', 'sensor.kristians_macbook_pro_last_update_trigger', 'sensor.kristians_macbook_pro_primary_display_id', 'sensor.kristians_macbook_pro_primary_display_name', 'sensor.kristians_macbook_pro_ssid', 'sensor.kristians_macbook_pro_storage', 'sensor.livingroom_room_humidity_status', 'sensor.load_15m', 'sensor.load_5m', 'sensor.nas_cpu_load_15_min', 'sensor.nas_cpu_load_5_min', 'sensor.nas_cpu_load_total', 'sensor.nas_cpu_load_user', 'sensor.nas_drive_1_status', 'sensor.nas_drive_2_status', 'sensor.nas_memory_usage_real', 'sensor.nas_volume_1_status', 'sensor.nas_volume_1_volume_used', 'sensor.nas_volume_2_status', 'sensor.nas_volume_2_volume_used', 'sensor.nas_volume_3_status', 'sensor.nas_volume_3_volume_used', 'sensor.our_groceries', 'sensor.pixel_7a_battery_state', 'sensor.pixel_7a_charger_type', 'sensor.pixel_7a_detected_activity', 'sensor.pixel_7a_do_not_disturb_sensor', 'sensor.pixel_7a_sleep_confidence', 'sensor.pixel_7a_wifi_connection', 'sensor.processor_use_percent', 'sensor.studio_room_humidity_status', 'sensor.time', 'update.duck_dns_update', 'update.file_editor_update', 'update.glances_update', 'update.grafana_update', 'update.home_assistant_core_update', 'update.home_assistant_google_drive_backup_update', 'update.home_assistant_operating_system_update', 'update.home_assistant_supervisor_update', 'update.influxdb_update', 'update.log_viewer_update', 'update.mariadb_update', 'update.mosquitto_broker_update', 'update.nas_dsm_update', 'update.nginx_proxy_manager_update', 'update.phpmyadmin_update', 'update.portainer_update', 'update.rclone_backup_update', 'update.samba_share_update', 'update.ssh_web_terminal_update', 'update.studio_code_server_update', 'update.unifi_network_application_update', 'update.wireguard_update', 'weather.hem']
2024-01-04 12:56:26.496 DEBUG (MainThread) [custom_components.thermal_comfort.config_flow] Results for temperature based on device class: ['sensor.balcony_outside_ceiling_temperature', 'sensor.balcony_outside_yard_temperature', 'sensor.bedroom_outside_balcony_temperature', 'sensor.bedroom_room_temperature', 'sensor.kitchen_freezer_mid_temperature', 'sensor.kitchen_freezer_top_temperature', 'sensor.kitchen_fridge_temperature', 'sensor.kitchen_pantry_temperature', 'sensor.kitchen_room_temperature', 'sensor.kitchen_unused_int_temperature', 'sensor.livingroom_room_real_temperature', 'sensor.livingroom_room_temperature', 'sensor.nas_drive_1_temperature', 'sensor.nas_drive_2_temperature', 'sensor.nas_temperature', 'sensor.nas_volume_1_average_disk_temp', 'sensor.nas_volume_2_average_disk_temp', 'sensor.nas_volume_3_average_disk_temp', 'sensor.outside_temperature', 'sensor.processor_temperature', 'sensor.studio_outside_street_temperature', 'sensor.studio_room_temperature']
2024-01-04 12:56:26.516 DEBUG (MainThread) [custom_components.thermal_comfort.config_flow] Additional results: ['input_boolean.autovoice_lan_enabled', 'input_boolean.bedroom_mattress_timer', 'input_boolean.livingroom_pir_sensor_activated', 'input_boolean.main_phone_home_wifi', 'input_boolean.main_phone_nightmode', 'input_boolean.smoke_detector_alarm_sent', 'input_button.all_off', 'input_button.bright_light', 'input_button.helgmys', 'input_button.kvallsmys', 'input_button.movie_lights', 'input_button.night_off', 'input_datetime.rclone_last_successful_run', 'input_number.apartment_energy_spent_cost', 'input_number.kwh_price', 'remember_the_milk.kristian', 'select.harmony_hub_activities', 'sensor.apartment_smoke_detectors_sensor_status', 'sensor.backup_state', 'sensor.balcony_outside_ceiling_humidity_status', 'sensor.bedroom_room_humidity_status', 'sensor.brother_dcp_l2530dw_series', 'sensor.date', 'sensor.dcp_l2530dw_drum_counter', 'sensor.dcp_l2530dw_drum_remaining_pages', 'sensor.dcp_l2530dw_duplex_unit_pages_counter', 'sensor.dcp_l2530dw_page_counter', 'sensor.dcp_l2530dw_status', 'sensor.hacs', 'sensor.kitchen_pantry_humidity_status', 'sensor.kitchen_room_humidity_status', 'sensor.kitchen_unused_int_humidity_status', 'sensor.kristians_macbook_pro_active_audio_output', 'sensor.kristians_macbook_pro_active_camera', 'sensor.kristians_macbook_pro_active_microphone', 'sensor.kristians_macbook_pro_bssid', 'sensor.kristians_macbook_pro_connection_type', 'sensor.kristians_macbook_pro_displays', 'sensor.kristians_macbook_pro_frontmost_app', 'sensor.kristians_macbook_pro_geocoded_location', 'sensor.kristians_macbook_pro_internal_battery_state', 'sensor.kristians_macbook_pro_last_update_trigger', 'sensor.kristians_macbook_pro_primary_display_id', 'sensor.kristians_macbook_pro_primary_display_name', 'sensor.kristians_macbook_pro_ssid', 'sensor.kristians_macbook_pro_storage', 'sensor.kyl_estimated_watertemp_middle', 'sensor.livingroom_room_humidity_status', 'sensor.load_15m', 'sensor.load_5m', 'sensor.nas_cpu_load_15_min', 'sensor.nas_cpu_load_5_min', 'sensor.nas_drive_1_status', 'sensor.nas_drive_2_status', 'sensor.nas_volume_1_status', 'sensor.nas_volume_2_status', 'sensor.nas_volume_3_status', 'sensor.our_groceries', 'sensor.pixel_7a_battery_state', 'sensor.pixel_7a_charger_type', 'sensor.pixel_7a_detected_activity', 'sensor.pixel_7a_do_not_disturb_sensor', 'sensor.pixel_7a_wifi_connection', 'sensor.studio_room_humidity_status', 'sensor.time', 'update.duck_dns_update', 'update.file_editor_update', 'update.glances_update', 'update.grafana_update', 'update.home_assistant_core_update', 'update.home_assistant_google_drive_backup_update', 'update.home_assistant_operating_system_update', 'update.home_assistant_supervisor_update', 'update.influxdb_update', 'update.log_viewer_update', 'update.mariadb_update', 'update.mosquitto_broker_update', 'update.nas_dsm_update', 'update.nginx_proxy_manager_update', 'update.phpmyadmin_update', 'update.portainer_update', 'update.rclone_backup_update', 'update.samba_share_update', 'update.ssh_web_terminal_update', 'update.studio_code_server_update', 'update.unifi_network_application_update', 'update.wireguard_update', 'weather.hem']
2024-01-04 12:56:26.518 DEBUG (MainThread) [custom_components.thermal_comfort.config_flow] Results after cleaning own entities: ['sensor.balcony_outside_ceiling_temperature', 'sensor.balcony_outside_yard_temperature', 'sensor.bedroom_outside_balcony_temperature', 'sensor.bedroom_room_temperature', 'sensor.kitchen_freezer_mid_temperature', 'sensor.kitchen_freezer_top_temperature', 'sensor.kitchen_fridge_temperature', 'sensor.kitchen_pantry_temperature', 'sensor.kitchen_room_temperature', 'sensor.kitchen_unused_int_temperature', 'sensor.livingroom_room_real_temperature', 'sensor.livingroom_room_temperature', 'sensor.nas_drive_1_temperature', 'sensor.nas_drive_2_temperature', 'sensor.nas_temperature', 'sensor.nas_volume_1_average_disk_temp', 'sensor.nas_volume_2_average_disk_temp', 'sensor.nas_volume_3_average_disk_temp', 'sensor.outside_temperature', 'sensor.processor_temperature', 'sensor.studio_outside_street_temperature', 'sensor.studio_room_temperature', 'input_boolean.autovoice_lan_enabled', 'input_boolean.bedroom_mattress_timer', 'input_boolean.livingroom_pir_sensor_activated', 'input_boolean.main_phone_home_wifi', 'input_boolean.main_phone_nightmode', 'input_boolean.smoke_detector_alarm_sent', 'input_button.all_off', 'input_button.bright_light', 'input_button.helgmys', 'input_button.kvallsmys', 'input_button.movie_lights', 'input_button.night_off', 'input_datetime.rclone_last_successful_run', 'input_number.apartment_energy_spent_cost', 'input_number.kwh_price', 'remember_the_milk.kristian', 'select.harmony_hub_activities', 'sensor.apartment_smoke_detectors_sensor_status', 'sensor.backup_state', 'sensor.balcony_outside_ceiling_humidity_status', 'sensor.bedroom_room_humidity_status', 'sensor.brother_dcp_l2530dw_series', 'sensor.date', 'sensor.dcp_l2530dw_drum_counter', 'sensor.dcp_l2530dw_drum_remaining_pages', 'sensor.dcp_l2530dw_duplex_unit_pages_counter', 'sensor.dcp_l2530dw_page_counter', 'sensor.dcp_l2530dw_status', 'sensor.hacs', 'sensor.kitchen_pantry_humidity_status', 'sensor.kitchen_room_humidity_status', 'sensor.kitchen_unused_int_humidity_status', 'sensor.kristians_macbook_pro_active_audio_output', 'sensor.kristians_macbook_pro_active_camera', 'sensor.kristians_macbook_pro_active_microphone', 'sensor.kristians_macbook_pro_bssid', 'sensor.kristians_macbook_pro_connection_type', 'sensor.kristians_macbook_pro_displays', 'sensor.kristians_macbook_pro_frontmost_app', 'sensor.kristians_macbook_pro_geocoded_location', 'sensor.kristians_macbook_pro_internal_battery_state', 'sensor.kristians_macbook_pro_last_update_trigger', 'sensor.kristians_macbook_pro_primary_display_id', 'sensor.kristians_macbook_pro_primary_display_name', 'sensor.kristians_macbook_pro_ssid', 'sensor.kristians_macbook_pro_storage', 'sensor.kyl_estimated_watertemp_middle', 'sensor.livingroom_room_humidity_status', 'sensor.load_15m', 'sensor.load_5m', 'sensor.nas_cpu_load_15_min', 'sensor.nas_cpu_load_5_min', 'sensor.nas_drive_1_status', 'sensor.nas_drive_2_status', 'sensor.nas_volume_1_status', 'sensor.nas_volume_2_status', 'sensor.nas_volume_3_status', 'sensor.our_groceries', 'sensor.pixel_7a_battery_state', 'sensor.pixel_7a_charger_type', 'sensor.pixel_7a_detected_activity', 'sensor.pixel_7a_do_not_disturb_sensor', 'sensor.pixel_7a_wifi_connection', 'sensor.studio_room_humidity_status', 'sensor.time', 'update.duck_dns_update', 'update.file_editor_update', 'update.glances_update', 'update.grafana_update', 'update.home_assistant_core_update', 'update.home_assistant_google_drive_backup_update', 'update.home_assistant_operating_system_update', 'update.home_assistant_supervisor_update', 'update.influxdb_update', 'update.log_viewer_update', 'update.mariadb_update', 'update.mosquitto_broker_update', 'update.nas_dsm_update', 'update.nginx_proxy_manager_update', 'update.phpmyadmin_update', 'update.portainer_update', 'update.rclone_backup_update', 'update.samba_share_update', 'update.ssh_web_terminal_update', 'update.studio_code_server_update', 'update.unifi_network_application_update', 'update.wireguard_update', 'weather.hem']
2024-01-04 12:56:46.892 DEBUG (MainThread) [custom_components.thermal_comfort.config_flow] Going to use t_sensor RegistryEntry(entity_id='sensor.outside_temperature', unique_id='515d0cba365336ce13188bfaedd4e703', platform='template', previous_unique_id=None, aliases=set(), area_id=None, capabilities={'state_class': 'measurement'}, config_entry_id='515d0cba365336ce13188bfaedd4e703', device_class=None, device_id=None, disabled_by=None, entity_category=None, hidden_by=None, icon=None, id='2162949eec1942c09ee64b298889bba4', has_entity_name=False, name=None, options={'conversation': {'should_expose': True}, 'sensor': {'display_precision': None}}, original_device_class='temperature', original_icon=None, original_name='Outside temperature', supported_features=0, translation_key=None, unit_of_measurement='°C')
2024-01-04 12:56:46.896 DEBUG (MainThread) [custom_components.thermal_comfort.config_flow] Going to use p_sensor RegistryEntry(entity_id='sensor.balcony_outside_ceiling_humidity', unique_id='52_9_e7:00_Humidity', platform='rfxtrx', previous_unique_id=None, aliases=set(), area_id=None, capabilities={'state_class': 'measurement'}, config_entry_id='cab8d85a1fa9f63b9a45461850c4e8bd', device_class=None, device_id='6a8af9f166d98c5e6c33f4cb7340b444', disabled_by=None, entity_category=None, hidden_by=None, icon=None, id='75fac01656ad37bdef642038e9d209b7', has_entity_name=True, name=None, options={'conversation': {'should_expose': True}}, original_device_class='humidity', original_icon=None, original_name='Humidity', supported_features=0, translation_key=None, unit_of_measurement='%')
2024-01-04 12:56:46.905 DEBUG (MainThread) [custom_components.thermal_comfort.sensor] async_setup_entry: {'name': 'Thermal Comfort', 'temperature_sensor': 'sensor.outside_temperature', 'humidity_sensor': 'sensor.balcony_outside_ceiling_humidity', 'poll': True, 'scan_interval': 300, 'custom_icons': False, 'enabled_sensors': ['dew_point'], 'update_listener': <function ConfigEntry.add_update_listener.<locals>.<lambda> at 0x7f647daac0>}
2024-01-04 12:56:46.909 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up thermal_comfort platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermal_comfort/sensor.py", line 443, in async_setup_entry
    entity.entity_description.entity_registry_enabled_default = False
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'entity_registry_enabled_default'
2024-01-04 12:56:55.539 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 883, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 912, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 529, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/melcloud/sensor.py", line 188, in native_value
    return self.entity_description.value_fn(self._api)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/melcloud/sensor.py", line 68, in 
    value_fn=lambda x: x.device.daily_energy_consumed,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymelcloud/device.py", line 210, in daily_energy_consumed
    consumption += self._energy_report.get(mode, [0.0])[-1]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2024-01-04 12:57:25.538 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 883, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 912, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 529, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/melcloud/sensor.py", line 188, in native_value
    return self.entity_description.value_fn(self._api)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/melcloud/sensor.py", line 68, in 
    value_fn=lambda x: x.device.daily_energy_consumed,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymelcloud/device.py", line 210, in daily_energy_consumed
    consumption += self._energy_report.get(mode, [0.0])[-1]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
ConnectedDDisconnectSDisable Autoscroll⌘KClear Console`

**Comment by rautesamtr** [comment]
Thank you. Found the issue. As i'm currently traveling i can't release a fix today, but tomorrow.

**Comment by tigersoul925** [comment]
Awesome, glad I could help finding it.

**Comment by cRemE-fReSh** [comment]
Happy new year!

I got the same issue.

Thank you @rautesamtr in advance for fixing it!

**Comment by pops106** [comment]
Same for me 2.2.1 just popped up and working fine again.

Thanks @rautesamtr

**Comment by tigersoul925** [comment]
For me, 2.2.1 still won't work correctly. When I first add my settings, no entities are created. I have to click configure and submit, then entities are added and it updates, but now my setting of only calculating dew point is forgotten.

**Comment by rautesamtr** [comment]
@tigersoul925  2.2.2 is released, can you give it a try?

**Comment by tigersoul925** [comment]
> @tigersoul925 2.2.2 is released, can you give it a try?

Worked fine on first attempt. Now just hoping that it keeps working after restarting HA as that was another issue but it might be related 🤞

**Comment by thwe1966** [comment]
> @tigersoul925 2.2.2 is released, can you give it a try?

Everything is working again for me, thanks for the quick fix
