### ISSUE TITLE
HA Startup errors: STATE_UNKNOWN, STATE_UNAVAILABLE

### ISSUE THREAD

**Issue by VDRainer** [dolezsa/thermal_comfort#37]
SInce last update i'm getting lots of errors on HA Start.
```
ValueError: could not convert string to float: 'unavailable'
2021-12-13 09:25:05 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassi/.homeassistant/custom_components/thermal_comfort/sensor.py", line 152, in humidity_state_listener
    if _is_valid_state(new_state):
  File "/home/homeassi/.homeassistant/custom_components/thermal_comfort/sensor.py", line 282, in _is_valid_state
    return state and state.state not in (STATE_UNKNOWN, STATE_UNAVAILABLE, math.isnan(float(state.state)))
ValueError: could not convert string to float: 'unknown'
2021-12-13 09:25:05 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassi/.homeassistant/custom_components/thermal_comfort/sensor.py", line 152, in humidity_state_listener
    if _is_valid_state(new_state):
  File "/home/homeassi/.homeassistant/custom_components/thermal_comfort/sensor.py", line 282, in _is_valid_state
    return state and state.state not in (STATE_UNKNOWN, STATE_UNAVAILABLE, math.isnan(float(state.state)))
```

**Comment by rautesamtr** [comment]
Hi @johnboiles, i am really sorry for the inconvenience. I am still getting the testing system together, and the tests for this case where still missing. I shouldn't have pushed those changes.

**Comment by VDRainer** [comment]
Thanks for your quick fix!
